apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-dpl
spec:
  selector:
    matchLabels:
      app: product
  replicas: 1
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product-service-container
          image: 4ixser/hw3:$PS_TAG
          imagePullPolicy: Always
          resources:
            limits:
              memony: "512Mi"
              cpu: "500m"
            requests:
              memony: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: product-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: product
